export const dashboardData = [
    { title: "Today Order", count: 0, bg: "bg-blue-500", icon: "fas fa-shopping-cart" },
    { title: "Today Pending Order", count: 0, bg: "bg-blue-500", icon: "fas fa-shopping-cart" },
    { title: "Total Order", count: 0, bg: "bg-blue-500", icon: "fas fa-shopping-cart" },
    { title: "Total Pending Order", count: 20, bg: "bg-blue-500", icon: "fas fa-shopping-cart" },
    { title: "Total Declined Order", count: 0, bg: "bg-orange-500", icon: "fas fa-shopping-cart" },
    { title: "Total Complete Order", count: 1, bg: "bg-orange-500", icon: "fas fa-shopping-cart" },
    { title: "Today Earning", count: 0, bg: "bg-orange-500", icon: "fas fa-wallet" },
    { title: "Today Pending Earning", count: 0, bg: "bg-orange-500", icon: "fas fa-wallet" },
    { title: "This Month Earning", count: 0, bg: "bg-green-500", icon: "fas fa-wallet" },
    { title: "This Year Earning", count: 0, bg: "bg-green-500", icon: "fas fa-wallet" },
    { title: "Total Earning", count: 0, bg: "bg-green-500", icon: "fas fa-wallet" },
    { title: "Today Product Sale", count: 0, bg: "bg-green-500", icon: "fas fa-box" },
    { title: "This Month Product Sale", count: 0, bg: "bg-red-500", icon: "fas fa-box" },
    { title: "This Year Product Sale", count: 2, bg: "bg-red-500", icon: "fas fa-box" },
    { title: "Total Product Sale", count: 2, bg: "bg-red-500", icon: "fas fa-box" },
    { title: "Total Product", count: 44, bg: "bg-red-500", icon: "fas fa-check-circle" },
    { title: "Total Product Report", count: 0, bg: "bg-green-500", icon: "fas fa-file-alt" },
    { title: "Total Product Review", count: 13, bg: "bg-green-500", icon: "fas fa-star" },
    { title: "Total Seller", count: 9, bg: "bg-green-500", icon: "fas fa-user" },
    { title: "Total User", count: 91, bg: "bg-green-500", icon: "fas fa-users" },
  ];
  